export const terms = [
  {
    term: 'Climate',
    definition: 'The average weather conditions in an area in general or over a long period.',
    link: 'climate'
  },
  {
    term: 'Weather',
    definition: 'The state of the atmosphere at a place and time as regards temperature, humidity, sunlight, wind, or precipitation',
    link: 'weather'
  },
  {
    term: 'Greenhouse gases',
    definition: 'Any gases that contribute to the greenhouse effect by absorbing infrared radiation.',
    link: 'greenhousegases'
  },
  {
    term: 'Climate change',
    definition: "Current and future changes in the Earth's climate caused by global warming.",
    link: 'climatechange'
  },
  {
    term: 'Global warming',
    definition: "The long-term heating of Earth's surface observed since the pre-industrial period.",
    link: 'globalwarming'
  },
  {
    term: 'Carbon tax',
    definition: 'A proposed tax on all carbon producers in hopes to reduce its use.',
    link: 'carbontax'
  },
{
    term: 'Permafrost',
    definition: 'A thick subsurface layer of soil that remains frozen throughout the year, mainly found in polar regions.',
    link: 'permafrost'
  },
  {
    term: 'Carbon footprint',
    definition: 'The total amount of greenhouse gasses (including carbon dioxide and methane) that are generated by our actions.'
  },
  {
    term: 'Mitigation',
    definition: 'Any attempts made to limit greenhouse gas emissions.'
  },
  {
    term: 'Tipping point',
    definition: 'A critical point in climate change when the planet warms enough to release a cascade of unstoppable, devastating changes'
  },
  {
    term: 'Emissions',
    definition: 'When greenhouse gasses are released into the air through human activity.'
  },
  {
    term: 'Sea-level rise',
    definition: 'Due to the warming of the oceans and the melting of the glaciers and sea ice, the sea-level is expected to rise substantially'
  },
  {
    term: 'Renewable energy',
    definition: 'Energy comes from naturally replenished sources that don’t release greenhouse gasses.'
  },
  {
    term: 'PPM',
    definition: 'The abbreviation of the unit parts per million commonly used in assessing the amount of pollutants in our atmosphere.'
  },
  {
    term: 'Carbon dioxide',
    definition: 'A colorless, odorless greenhouse gas found in our atmosphere consisting of one carbon atom bonded to two oxygen atoms.(CO2) This gas is the main contributor to climate change.'
  },
  {
    term: 'Methane',
    definition: 'A colorless, odorless greenhouse gas found in our atmosphere consisting of one carbon atom bonded to four hydrogen atoms.(CH4) The second biggest contributor to climate change, it absorbs 84 times more heat than carbon dioxide.'
  },
  {
    
    term: 'Carbon cycle',
    definition: 'The movement of carbon through an environment, mainly found in life, the atmosphere, or underground.'
  },


]